apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  labels:
    app: marketing-mock
  name: marketing-mock
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - marketing
  service:
    name: marketing-mock
    port: 10000
  rules:
    - path: /*
      methods: ["GET","POST","PUT","DELETE","HEAD"]
      noAuth: true
