apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: event-subscription
  namespace: conference-registration
spec:
  source: ""
  types:
    - sap.kyma.custom.app.conference.registration.v1
  typeMatching: exact
  sink: http://event-consumer.conference-registration.svc.cluster.local
