apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{ include "sample-extension-micronaut.fullname" . }}
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - {{ .Chart.Name }}
  rules:
    - noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /*
  service:
    name: {{ include "sample-extension-micronaut.fullname" . }}
    port: 80