apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: {{ include "sample-event-trigger-java.fullname" . }}
  labels:
    {{- include "sample-event-trigger-java.labels" . | nindent 4 }}
spec:
  source: ""
  types:
    - sap.kyma.custom.{{ .Values.subscription.application }}.{{ .Values.subscription.eventType }}.v1
  typeMatching: exact
  sink: http://{{ include "sample-event-trigger-java.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
