apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: { { include "api-mssql-go.fullname" . } }
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - { { include "api-mssql-go.fullname" . } }
  service:
    name: { { include "api-mssql-go.fullname" . } }
    port: { { .Values.service.port } }
  rules:
    - path: /orders/{**}
      noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
