apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: sample-event-trigger-java-subscription
spec:
  source: ""
  types:
    - sap.kyma.custom.{your-connected-commerce-application-name}.order.created.v1
  typeMatching: exact
  sink: http://sample-event-trigger-java.dev.svc.cluster.local
