apiVersion: telemetry.kyma-project.io/v1beta1
kind: LogPipeline
metadata:
  name: my-cls
spec:
  input:
    runtime:
      enabled: true
  output:
    otlp:
      endpoint:
        valueFrom:
          secretKeyRef:
            name: my-cls-binding
            namespace: cls
            key: ingest-otlp-endpoint
      tls:
        cert:
          valueFrom:
            secretKeyRef:
              name: my-cls-binding
              namespace: cls
              key: ingest-otlp-cert
        key:
          valueFrom:
            secretKeyRef:
              name: my-cls-binding
              namespace: cls
              key: ingest-otlp-key
