apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: event-registration-subscription
  namespace: cdc
spec:
  source: ""
  types:
    - sap.kyma.custom.cdc.subscription.updated.v1
  typeMatching: exact
  sink: http://event-consumer.cdc.svc.cluster.local
