apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  labels:
    sample: principal-prop-on-prem
  name: principal-prop-on-prem
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - principal-prop-on-prem
  rules:
    - path: /*
      methods: ["GET", "POST", "PUT", "DELETE"]
      noAuth: true
      service:
        name: app-router
        port: 5000
