apiVersion: v1
kind: ConfigMap
metadata:
  name: destinations
data:
  destinations: >-
    [
        {
          "name": "on-prem-backend-tp",
          "url": "http://principal-prop-on-prem-dest.sap-transp-proxy-system",
          "forwardAuthToken": true
        }
    ]
---
apiVersion: v1
data:
  xs-app.json: |-
    {
        "authenticationMethod": "route",
        "sessionTimeout": 10,
        "login" : {
          "callbackEndpoint": "/sap/com/onprem/mysales"
        },
        "routes": [
            {
                "source": "^/sap/com/onprem/(.*)$",
                "destination": "on-prem-backend-tp",
                "target": "$1",
                "authenticationType": "none"
            }
        ]
    }
kind: ConfigMap
metadata:
  name: approuter-config
  labels:
    sample: principal-prop-on-prem