apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{ include "sample-dot-net.fullname" . }}
  labels:
    {{- include "sample-dot-net.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.apirule.gateway }}
  hosts:
    - {{ .Chart.Name }}-{{ .Release.Namespace }}
  rules:
    {{- if .Values.apirule.jwt.enabled }}
    - jwt:
        authentications:
          {{- range .Values.apirule.jwt.authentications }}
          - issuer: {{ .issuer }}
            jwksUri: {{ .jwksUri }}
          {{- end }}
      methods:
        - GET
      path: /*
    {{- else }}
    - noAuth: true
      methods:
        - GET
      path: /*
    {{- end }}
  service:
    name: {{ include "sample-dot-net.fullname" . }}
    port: {{ .Values.service.port }}
