apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: supplychaintrigger
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - supplychaintrigger.<YOUR HOST>
  rules:
    - noAuth: true
      methods:
        - POST
        - GET
      path: /*
  service:
    name: triggersupplyshortagemessage
    port: 80