apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: order-validation
spec:
  source: ""
  types:
    - sap.kyma.custom.<ccv2-application>.order.fraudcheck.v1
  typeMatching: exact
  sink: http://order-validation.order-validation.svc.cluster.local
