apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: consumer
  labels:
    scenario: in-cluster-events
spec:
  source: ""
  types:
    - sap.kyma.custom.internal.product.viewed.v1
  typeMatching: exact
  sink: http://consumer.in-cluster-events.svc.cluster.local
