apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{ include "sample-extension-dotnet-minimalapi.fullname" . }}
  labels:
    {{- include "sample-extension-dotnet-minimalapi.labels" . | nindent 4 }}
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - {{ .Chart.Name }}
  rules:
    - noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /*
  service:
    name: {{ include "sample-extension-dotnet-minimalapi.fullname" . }}
    port: {{ .Values.service.port }}