apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: bot-observer-apirule
spec:
  gateway: {{ .Values.bot.botobservertool.apirule.gateway }}
  hosts: 
  - bot-observer
  rules:
  - noAuth: true
    methods:
    - GET
    path: /*
    service:
      name: bot-observer-service
      port: {{ .Values.bot.botobservertool.apirule.port }}
