apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{include "frontend-ui5-mssql.fullname" .}}
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - {{include "frontend-ui5-mssql.fullname" .}}
  service:
    name: {{include "frontend-ui5-mssql.fullname" .}}
    port: {{.Values.service.port}}
  rules:
    - path: /*
      noAuth: true
      methods:
        - GET
